### ISSUE TITLE
Hosted demo does not work

### ISSUE THREAD

**Issue by stephane-vanraes** [beyonk-adventures/svelte-steps#1]
Recently (v1.2?) the concept of the `current` store was introduced.
The demo on [REPL](https://svelte.dev/repl/c3a67f7c8df047f484a5dd717ac59f16?version=3.24.1l) does not seem to have picked up this change.

Changes to be made:

import current from the library
```html
import { Steps, Pages, setup, current } from '@beyonk/svelte-steps'
```

bind input to the current store
```html
zinput type="range" min=0 max=2 bind:value={$current}/> {$current}
```

remove property current from Steps
```html
<Steps {theme} />
```

**Comment by antony** [comment]
Agreed! All working again now. Thanks!
